### ISSUE TITLE
Support gradle 1.5+

### ISSUE THREAD

**Issue by autovalue** [mbiamont/google-analytics-annotations#1]
Hi, awesome gradle plugin.

While testing the new Instant Run feature in gradle/Android studio, I found that the library no longer supported gradle 1.5+, because it still referenced the [dex method](https://github.com/mbiamont/google-analytics-annotations/blob/master/ga-annotations-plugin/src/main/groovy/com/mbiamont/ga_annotations/plugin/GAAnnotationsPlugin.groovy#L33).

http://tools.android.com/tech-docs/new-build-system/transform-api

Do you think it would be possible to add a 2.0 version of the app to support gradle 1.5+?

Thanks.

**Comment by renaudcerrato** [comment]
Just sent a PR (https://github.com/mbiamont/google-analytics-annotations/pull/2) with the modification needed to make it works on Gradle 1.5

**Comment by mbiamont** [comment]
Fixed in Version 1.1.0
