### ISSUE TITLE
Track screen fragment

### ISSUE THREAD

**Issue by amouly** [mbiamont/google-analytics-annotations#4]
There is a way to track the "screen event" when entering on Fragments? I see the Activity example but not Fragment example or documentation.

Thanks for your help.

**Comment by mbiamont** [comment]
Hi,

Yes; you can use the annotation on fragments too :)

Example :

```
@TrackScreen(name = "MainFragment")
@Override
protected void onActivityCreated(Bundle savedInstanceState) {
  super.onActivityCreated(savedInstanceState);
  (...)
}
```
