### ISSUE TITLE
 java.lang.NullPointerException  Api 18 (sony xperia)

### ISSUE THREAD

**Issue by kirvis250** [mbiamont/google-analytics-annotations#7]
java.lang.NullPointerException at com.mbiamont.ga_annotations.aspect.TrackScreenAspect.sendTrack(TrackScreenAspect.java:44). 

Same code works on  nexus 5x (24 api level) but fails in 18 Api level sony xperia sp.

**Comment by badoualy** [comment]
Same bug
- Samsung Galaxy Ace 4 API 19
- Samsung Note 3 API 19

**Comment by mbiamont** [comment]
Hi, the bug should be fixed using the plugin version 1.1.1 and the library 1.2.1
